apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hddl
  labels:
    app: hddl
spec:
  selector:
    matchLabels:
      name: hddl
  template:
    metadata:
      labels:
        name: hddl
    spec:
      containers:
      - name: hddl
        image: gar-registry.caas.intel.com/virtiot/hddl:1.0
        securityContext:
          privileged: true
        command: [ "/run_hddl_service.sh"]
        volumeMounts:
        - mountPath: /dev/xlnk
          name: xlnk
        - mountPath: /var/tmp
          name: socket
      volumes:
      - name: socket
        hostPath:
          path: /tmp
      - name: xlnk
        hostPath:
          path: /dev/xlnk

