apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kmb-plugin
  namespace: kube-system
  labels:
    app: kmb-plugin
spec:
  selector:
    matchLabels:
      name: kmb-plugin
  template:
    metadata:
      labels:
        name: kmb-plugin
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - name: kmb-plugin
        image: ubuntu
        command: [ "/usr/bin/kmb_plugin"]
        volumeMounts:
        - mountPath: /dev/xlnk
          name: kmb-xlnk
        - mountPath: /dev/mem
          name: kmb-mem
        - mountPath: /dev/vpusmm0
          name: kmb-vpusmm
        - mountPath: /dev/dri/renderD129
          name: kmb-vaapi
        - mountPath: /data/kmb
          name: kmb-vol
        - mountPath: /var/lib/kubelet/device-plugins
          name: kmb-socket
        - mountPath: /usr/bin/kmb_plugin
          name: kmb-plugin
      volumes:
      - name: kmb-plugin
        hostPath:
          path: /etc/edge-ai/device-plugin/kmb_plugin
      - name: kmb-xlnk
        hostPath:
          path: /dev/xlnk
      - name: kmb-mem
        hostPath:
          path: /dev/mem
      - name: kmb-vpusmm
        hostPath:
          path: /dev/vpusmm0
      - name: kmb-vaapi
        hostPath:
          path: /dev/dri/renderD129
      - name: kmb-vol
        hostPath:
          path: /data/kmb
          type: Directory
      - name: kmb-socket
        hostPath:
          path: /var/lib/kubelet/device-plugins
          type: Directory

