FROM alpine:latest

COPY hddl_plugin /hddl_plugin
RUN apk update
RUN apk add --upgrade apk-tools-static
RUN apk add --upgrade openssl-dev
RUN apk add pciutils
RUN addgroup -g 1000 appgroup

# -D permits to create an user without password
RUN adduser -u 1000 -G appgroup -h /home/user -D user
USER user
