FROM ubuntu

RUN \
  apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install pciutils \
      && apt-get clean && \
        rm -rf /var/lib/apt/lists/*

COPY hddl_plugin /hddl_plugin

